import { ProtocolParameter } from "@/types/constants";

export const deviceTypes = [
  "TV",
  "Air Conditioner",
  "Sound System",
  "DVD Player",
  "Blu-ray Player",
  "Cable Box",
  "Satellite Receiver",
  "Streaming Device",
  "Projector",
  "Fan",
  "Heater",
  "Gaming Console",
  "Set-Top Box",
  "Audio Receiver",
  "Doorbell",
  "Light Switch",
  "Garage Door",
  "Other",
];

export const popularBrands = [
  "Samsung",
  "LG",
  "Sony",
  "Panasonic",
  "Philips",
  "TCL",
  "Hisense",
  "Sharp",
  "Toshiba",
  "Vizio",
  "Roku",
  "Apple",
  "Amazon",
  "Google",
  "Microsoft",
  "Nintendo",
  "Haier",
  "Midea",
  "Coolix",
  "Daikin",
  "Other",
];

export const esphomeProtocols = [
  { value: "nec", label: "NEC", description: "Most common IR protocol" },
  { value: "samsung", label: "Samsung", description: "Samsung devices" },
  {
    value: "samsung36",
    label: "Samsung36",
    description: "Samsung 36-bit protocol",
  },
  { value: "sony", label: "Sony", description: "Sony devices" },
  { value: "lg", label: "LG", description: "LG devices" },
  { value: "panasonic", label: "Panasonic", description: "Panasonic devices" },
  { value: "rc5", label: "RC5", description: "Philips RC5 protocol" },
  { value: "rc6", label: "RC6", description: "Philips RC6 protocol" },
  { value: "jvc", label: "JVC", description: "JVC devices" },
  { value: "pioneer", label: "Pioneer", description: "Pioneer devices" },
  { value: "coolix", label: "Coolix", description: "Air conditioner protocol" },
  { value: "midea", label: "Midea", description: "Midea air conditioners" },
  { value: "haier", label: "Haier", description: "Haier air conditioners" },
  {
    value: "toshiba_ac",
    label: "Toshiba AC",
    description: "Toshiba air conditioners",
  },
  { value: "mirage", label: "Mirage", description: "Mirage AC protocol" },
  {
    value: "dish",
    label: "Dish Network",
    description: "Dish Network receivers",
  },
  { value: "pronto", label: "Pronto", description: "Pronto hex codes" },
  { value: "raw", label: "Raw", description: "Raw timing data" },
  {
    value: "aeha",
    label: "AEHA",
    description: "AEHA protocol (Panasonic, etc.)",
  },
  { value: "beo4", label: "B&O Beo4", description: "Bang & Olufsen" },
  { value: "canalsat", label: "CanalSat", description: "CanalSat receivers" },
  {
    value: "canalsatld",
    label: "CanalSatLD",
    description: "CanalSat LD receivers",
  },
  {
    value: "rc_switch_raw",
    label: "RC Switch Raw",
    description: "433MHz RC Switch raw binary",
  },
  {
    value: "rc_switch_type_a",
    label: "RC Switch Type A",
    description: "433MHz RC Switch Type A",
  },
  {
    value: "rc_switch_type_b",
    label: "RC Switch Type B",
    description: "433MHz RC Switch Type B",
  },
  {
    value: "rc_switch_type_c",
    label: "RC Switch Type C",
    description: "433MHz RC Switch Type C",
  },
  {
    value: "rc_switch_type_d",
    label: "RC Switch Type D",
    description: "433MHz RC Switch Type D",
  },
  { value: "nexa", label: "Nexa", description: "Nexa RF protocol" },
  { value: "keeloq", label: "KeeLoq", description: "KeeLoq RF protocol" },
  { value: "dooya", label: "Dooya", description: "Dooya RF protocol" },
  { value: "byronsx", label: "Byron SX", description: "Byron SX doorbell" },
  { value: "drayton", label: "Drayton", description: "Drayton Digistat" },
  { value: "magiquest", label: "MagiQuest", description: "MagiQuest wands" },
  { value: "roomba", label: "Roomba", description: "iRobot Roomba" },
  {
    value: "abbwelcome",
    label: "ABB Welcome",
    description: "ABB Welcome intercom system",
  },
  { value: "gobox", label: "Go-Box", description: "Go-Box IR protocol" },
  { value: "toto", label: "Toto", description: "Toto bidet/toilet protocol" },
];

export const protocolParameters: Record<string, ProtocolParameter[]> = {
  nec: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "16-bit device address.",
      placeholder: "0x1234",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description:
        "16-bit command. Must contain the 8-bit command and its logical inverse. E.g., for command 0x37, use 0xC837.",
      placeholder: "0xC837",
    },
    {
      name: "command_repeats",
      label: "Command Repeats",
      type: "int",
      required: false,
      description: "Number of times the command bytes are sent (default: 1).",
      min: 1,
      skip: true,
    },
  ],
  samsung: [
    {
      name: "data",
      label: "Data",
      type: "int",
      required: true,
      description: "Samsung code data.",
      placeholder: "0xE0E040BF",
    },
    {
      name: "nbits",
      label: "Number of Bits",
      type: "int",
      required: false,
      description: "Number of bits (default: 32).",
      min: 1,
      max: 64,
      placeholder: "32",
    },
  ],
  samsung36: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "Address to send.",
      placeholder: "0x0400",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Samsung36 command to send.",
      placeholder: "0x000E00FF",
    },
  ],
  sony: [
    {
      name: "data",
      label: "Data",
      type: "int",
      required: true,
      description: "Sony code data.",
      placeholder: "0x240C",
    },
    {
      name: "nbits",
      label: "Number of Bits",
      type: "int",
      required: false,
      description: "Number of bits (default: 12).",
      min: 1,
      max: 64,
      placeholder: "12",
    },
  ],
  lg: [
    {
      name: "data",
      label: "Data",
      type: "int",
      required: true,
      description: "LG code data.",
      placeholder: "0x20DF10EF",
    },
    {
      name: "nbits",
      label: "Number of Bits",
      type: "int",
      required: false,
      description: "Number of bits (default: 28).",
      min: 1,
      max: 64,
      placeholder: "28",
    },
  ],
  panasonic: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "Device address.",
      placeholder: "0x4004",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command code.",
      placeholder: "0x100BCBD",
    },
  ],
  rc5: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "Device address (0-31).",
      min: 0,
      max: 31,
      placeholder: "1",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command code (0-63).",
      min: 0,
      max: 63,
      placeholder: "12",
    },
  ],
  rc6: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "Device address.",
      placeholder: "0",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command code.",
      placeholder: "12",
    },
  ],
  jvc: [
    {
      name: "data",
      label: "Data",
      type: "int",
      required: true,
      description: "JVC code data.",
      placeholder: "0xC5E8",
    },
  ],
  pioneer: [
    {
      name: "rc_code_1",
      label: "RC Code 1",
      type: "int",
      required: true,
      description: "Primary Pioneer remote code.",
      placeholder: "0xA55A38C7",
    },
    {
      name: "rc_code_2",
      label: "RC Code 2",
      type: "int",
      required: false,
      description: "Secondary Pioneer remote code (optional).",
      placeholder: "0xA506",
    },
  ],
  coolix: [
    {
      name: "first",
      label: "First Code",
      type: "int",
      required: true,
      description: "First 24-bit Coolix code.",
      placeholder: "0xB21F48",
    },
    {
      name: "second",
      label: "Second Code",
      type: "int",
      required: false,
      description: "Second 24-bit Coolix code (optional).",
      placeholder: "0xB21FC8",
    },
  ],
  midea: [
    {
      name: "code",
      label: "Code",
      type: "bytes",
      required: true,
      description: "5-byte Midea code array.",
      placeholder: "[0xA2, 0x08, 0xFF, 0xFF, 0xFF]",
      validation:
        /^\[\s*(0x[0-9A-Fa-f]{1,2}(\s*,\s*0x[0-9A-Fa-f]{1,2}){4})\s*\]$/,
    },
  ],
  haier: [
    {
      name: "code",
      label: "Code",
      type: "bytes",
      required: true,
      description: "13-byte Haier code array.",
      placeholder: "[0xA6, 0xDA, 0x00, ...]",
      validation:
        /^\[\s*(0x[0-9A-Fa-f]{1,2}(\s*,\s*0x[0-9A-Fa-f]{1,2}){12})\s*\]$/,
    },
  ],
  toshiba_ac: [
    {
      name: "rc_code_1",
      label: "RC Code 1",
      type: "int",
      required: true,
      description: "First remote code.",
      placeholder: "0xB24DBF4040BF",
    },
    {
      name: "rc_code_2",
      label: "RC Code 2",
      type: "int",
      required: false,
      description: "Second remote code (optional).",
      placeholder: "0xD5660001003C",
    },
  ],
  mirage: [
    {
      name: "code",
      label: "Code",
      type: "bytes",
      required: true,
      description: "14-byte Mirage code array.",
      placeholder: "[0x56, 0x77, 0x00, ...]",
      validation:
        /^\[\s*(0x[0-9A-Fa-f]{1,2}(\s*,\s*0x[0-9A-Fa-f]{1,2}){13})\s*\]$/,
    },
  ],
  dish: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: false,
      description: "Receiver number (1-16, default: 1).",
      min: 1,
      max: 16,
      placeholder: "1",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Dish command (0-63).",
      min: 0,
      max: 63,
      placeholder: "16",
    },
  ],
  pronto: [
    {
      name: "data",
      label: "Pronto Code",
      type: "string",
      required: true,
      description: "Pronto hex string.",
      placeholder: "0000 006C 0022 0002 015B 00AD ...",
      validation: /^[0-9A-Fa-f\s]+$/,
    },
  ],
  raw: [
    {
      name: "code",
      label: "Raw Code",
      type: "list",
      required: true,
      description: "Raw timing array (positive=ON, negative=OFF in µs).",
      placeholder: "[4500, -4500, 560, -560, ...]",
      validation: /^\[\s*(-?\d+(\s*,\s*-?\d+)*)\s*\]$/,
    },
  ],
  aeha: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "Address to send.",
      placeholder: "0x1FEF",
    },
    {
      name: "data",
      label: "Data",
      type: "bytes",
      required: true,
      description: "2-35 byte list.",
      placeholder: "[0x1F, 0x3E, 0x06, 0x5F]",
      validation:
        /^\[\s*(0x[0-9A-Fa-f]{1,2}(\s*,\s*0x[0-9A-Fa-f]{1,2}){1,34})\s*\]$/,
    },
  ],
  beo4: [
    {
      name: "source",
      label: "Source",
      type: "int",
      required: true,
      description: "8-bit source (e.g., 0x01=audio).",
      min: 0,
      max: 255,
      placeholder: "0x01",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command to send (e.g., 0x0d=mute).",
      placeholder: "0x0d",
    },
  ],
  byronsx: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "8-bit ID code.",
      min: 0,
      max: 255,
      placeholder: "0x4f",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command to send.",
      placeholder: "0x2",
    },
  ],
  canalsat: [
    {
      name: "device",
      label: "Device",
      type: "int",
      required: true,
      description: "Device to send to.",
      placeholder: "0x25",
    },
    {
      name: "address",
      label: "Address",
      type: "int",
      required: false,
      description: "Address or sub-device (default: 0).",
      placeholder: "0",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command to send.",
      placeholder: "0x02",
    },
  ],
  canalsatld: [
    {
      name: "device",
      label: "Device",
      type: "int",
      required: true,
      description: "Device to send to.",
      placeholder: "0x25",
    },
    {
      name: "address",
      label: "Address",
      type: "int",
      required: false,
      description: "Address or sub-device (default: 0).",
      placeholder: "0",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command to send.",
      placeholder: "0x02",
    },
  ],
  dooya: [
    {
      name: "id",
      label: "ID",
      type: "int",
      required: true,
      description: "24-bit ID code.",
      placeholder: "0x001612E5",
    },
    {
      name: "channel",
      label: "Channel",
      type: "int",
      required: true,
      description: "8-bit channel (0-255).",
      min: 0,
      max: 255,
      placeholder: "142",
    },
    {
      name: "button",
      label: "Button",
      type: "int",
      required: true,
      description: "4-bit button (0-15).",
      min: 0,
      max: 15,
      placeholder: "12",
    },
    {
      name: "check",
      label: "Check",
      type: "int",
      required: true,
      description: "4-bit check code.",
      min: 0,
      max: 15,
      placeholder: "3",
    },
  ],
  drayton: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "16-bit ID code.",
      placeholder: "0x6180",
    },
    {
      name: "channel",
      label: "Channel",
      type: "int",
      required: true,
      description: "Switch/channel (0-127).",
      min: 0,
      max: 127,
      placeholder: "0x12",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "Command to send (0-63).",
      min: 0,
      max: 63,
      placeholder: "0x02",
    },
  ],
  gobox: [
    {
      name: "code",
      label: "Code",
      type: "int",
      required: true,
      description: "Go-Box command code.",
      placeholder: "0xfa05",
    },
  ],
  keeloq: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "32-bit address.",
      placeholder: "0x57ffe7b",
    },
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "4-bit command/button code.",
      min: 0,
      max: 15,
      placeholder: "0x02",
    },
    {
      name: "code",
      label: "Code",
      type: "int",
      required: false,
      description: "32-bit encrypted field (optional).",
      placeholder: "0xd19ef0a9",
    },
    {
      name: "level",
      label: "Low Battery",
      type: "boolean",
      required: false,
      description: "Low battery level status bit (default: false).",
    },
  ],
  magiquest: [
    {
      name: "wand_id",
      label: "Wand ID",
      type: "int",
      required: true,
      description: "MagiQuest wand ID.",
      placeholder: "0x01234567",
    },
    {
      name: "magnitude",
      label: "Magnitude",
      type: "int",
      required: false,
      description: "Magnitude of swishes/swirls (optional).",
      placeholder: "0x080C",
    },
  ],
  nexa: [
    {
      name: "device",
      label: "Device",
      type: "int",
      required: true,
      description: "Nexa device code.",
      placeholder: "0x38DDB4A",
    },
    {
      name: "state",
      label: "State",
      type: "int",
      required: true,
      description: "Nexa state code (0=OFF, 1=ON, 2=DIM).",
      min: 0,
      max: 2,
      placeholder: "1",
    },
    {
      name: "group",
      label: "Group",
      type: "int",
      required: true,
      description: "Nexa group code.",
      placeholder: "0",
    },
    {
      name: "channel",
      label: "Channel",
      type: "int",
      required: true,
      description: "Nexa channel code.",
      placeholder: "15",
    },
    {
      name: "level",
      label: "Level",
      type: "int",
      required: true,
      description: "Nexa level code.",
      placeholder: "0",
    },
  ],
  roomba: [
    {
      name: "data",
      label: "Data",
      type: "int",
      required: true,
      description: "Roomba command code (e.g., 0x88 for clean).",
      placeholder: "0x88",
    },
  ],
  toto: [
    {
      name: "command",
      label: "Command",
      type: "int",
      required: true,
      description: "1-byte Toto command (0-255).",
      min: 0,
      max: 255,
      placeholder: "0xED",
    },
    {
      name: "rc_code_1",
      label: "RC Code 1",
      type: "int",
      required: false,
      description: "First 4-bit parameter (0-15, optional).",
      min: 0,
      max: 15,
      placeholder: "0x0",
    },
    {
      name: "rc_code_2",
      label: "RC Code 2",
      type: "int",
      required: false,
      description: "Second 4-bit parameter (0-15, optional).",
      min: 0,
      max: 15,
      placeholder: "0x0",
    },
  ],
  abbwelcome: [
    {
      name: "source_address",
      label: "Source Address",
      type: "int",
      required: true,
      description: "Source address.",
      placeholder: "0x1001",
    },
    {
      name: "destination_address",
      label: "Destination Address",
      type: "int",
      required: true,
      description: "Destination address.",
      placeholder: "0x4001",
    },
    {
      name: "three_byte_address",
      label: "Three Byte Address",
      type: "boolean",
      required: false,
      description: "Use 3-byte address length (default: false).",
    },
    {
      name: "retransmission",
      label: "Retransmission",
      type: "boolean",
      required: false,
      description: "Message is a re-transmission (default: false).",
    },
    {
      name: "message_type",
      label: "Message Type",
      type: "int",
      required: true,
      description: "Message type.",
      placeholder: "0x0d",
    },
    {
      name: "message_id",
      label: "Message ID",
      type: "int",
      required: false,
      description: "Message ID (optional, random if not set).",
    },
    {
      name: "data",
      label: "Data",
      type: "bytes",
      required: false,
      description: "0-7 byte list (optional).",
      placeholder: "[0xab, 0xcd, 0xef]",
      validation:
        /^\[\s*(0x[0-9A-Fa-f]{1,2}(\s*,\s*0x[0-9A-Fa-f]{1,2}){0,6})?\s*\]$/,
    },
  ],
  rc_switch_raw: [
    {
      name: "code",
      label: "Code",
      type: "string",
      required: true,
      description: "Raw binary code to send.",
      placeholder: "001010011001111101011011",
      validation: /^[01]+$/,
    },
  ],
  rc_switch_type_a: [
    {
      name: "group",
      label: "Group",
      type: "string",
      required: true,
      description: "Binary string for the group.",
      placeholder: "01001",
      validation: /^[01]+$/,
    },
    {
      name: "device",
      label: "Device",
      type: "string",
      required: true,
      description: "Binary string for the device.",
      placeholder: "10110",
      validation: /^[01]+$/,
    },
    {
      name: "state",
      label: "State",
      type: "boolean",
      required: true,
      description: "On/off state to send.",
    },
  ],
  rc_switch_type_b: [
    {
      name: "address",
      label: "Address",
      type: "int",
      required: true,
      description: "Address to send the command to.",
      placeholder: "4",
    },
    {
      name: "channel",
      label: "Channel",
      type: "int",
      required: true,
      description: "Channel to send the command to.",
      placeholder: "11",
    },
    {
      name: "state",
      label: "State",
      type: "boolean",
      required: true,
      description: "On/off state to send.",
    },
  ],
  rc_switch_type_c: [
    {
      name: "family",
      label: "Family",
      type: "string",
      required: true,
      description: "Family to send command to (a-p).",
      placeholder: "c",
      validation: /^[a-pA-P]$/,
    },
    {
      name: "group",
      label: "Group",
      type: "int",
      required: true,
      description: "Group to send command to (1-4).",
      min: 1,
      max: 4,
      placeholder: "3",
    },
    {
      name: "device",
      label: "Device",
      type: "int",
      required: true,
      description: "Device to send command to (1-4).",
      min: 1,
      max: 4,
      placeholder: "1",
    },
    {
      name: "state",
      label: "State",
      type: "boolean",
      required: true,
      description: "On/off state to send.",
    },
  ],
  rc_switch_type_d: [
    {
      name: "group",
      label: "Group",
      type: "int",
      required: true,
      description: "Group to send command to (1-4).",
      min: 1,
      max: 4,
      placeholder: "3",
    },
    {
      name: "device",
      label: "Device",
      type: "int",
      required: true,
      description: "Device to send command to (1-3).",
      min: 1,
      max: 3,
      placeholder: "1",
    },
    {
      name: "state",
      label: "State",
      type: "boolean",
      required: true,
      description: "On/off state to send.",
    },
  ],
};
